### ISSUE TITLE
Logical Regression is Not Working in Text Widget

### ISSUE THREAD

**Issue by vippk0000** [biolab/orange-widget-base#66]
##### Orange version

Version 3.25.0
Text mining widget version: 0.9.1
OS Windows 10 pro

##### Expected behavior

Should let me apply logical regression.

##### Actual behavior

I was practicing a workflow creation exercise in text mining widget exactly like a Youtube tutorial video: https://www.youtube.com/watch?v=zO_zwKZCULo&t=31s

My workflow: Corpus>Preprocess text>bag of words>logical regression
File selected in corpus is default: grimm-tales-selected.tab
But when I applied logical regression to bag words, it throws error code like this ( the error stays in loop).

`Traceback (most recent call last):

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 242, in __add_widget_for_node
    w = self.create_widget_for_node(node)

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 396, in create_widget_instance
    klass = name_lookup(desc.qualified_name)

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\orangecanvas\utils\__init__.py", line 80, in name_lookup
    module = __import__(module_name, fromlist=[class_name])

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\widgets\model\owlogisticregression.py", line 8, in <module>
    from Orange.widgets.utils.owlearnerwidget import OWBaseLearner

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\widgets\utils\owlearnerwidget.py", line 6, in <module>
    from Orange.modelling import Fitter, Learner, Model

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\modelling\__init__.py", line 6, in <module>
    from .ada_boost import *

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\modelling\ada_boost.py", line 2, in <module>
    from Orange.ensembles import (

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\ensembles\__init__.py", line 5, in <module>
    from .stack import *

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\ensembles\stack.py", line 92, in <module>
    class StackedClassificationLearner(StackedLearner, LearnerClassification):

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\ensembles\stack.py", line 100, in StackedClassificationLearner
    def __init__(self, learners, aggregate=LogisticRegressionLearner(), k=5,

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\classification\logistic_regression.py", line 46, in __init__
    self.params = vars()

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\base.py", line 505, in params
    self._params = self._get_sklparams(value)

  File "C:\Users\vippankumar\AppData\Local\Orange\lib\site-packages\Orange\base.py", line 512, in _get_sklparams
    assert spec.args[0] == "self"

IndexError: list index out of range`

##### Additional info (worksheets, data, screenshots, ...)

My workflow image:
![Error_logical regression](https://user-images.githubusercontent.com/65536161/82199423-4b9d7b00-991b-11ea-9d45-910828e2bdf8.PNG)

**Comment by ajdapretnar** [comment]
This is the wrong repository for this issue. That said, you need `scikit-learn < 0.23.0`. Downgrade the package and it should work.

**Comment by vippk0000** [comment]
Thank you for the answer. I am sorry for putting it in the wrong repository. You mean, to downgrade Orange version?

**Comment by ajdapretnar** [comment]
No, just the scikit-learn package. Since you are on Windows, you can open Orange Command Prompt (find it in your apps), then copy-paste the following command `conda install scikit-learn=0.22.2.post`.

**Comment by vippk0000** [comment]
Okay thank you very much. Let me give it a try.

**Comment by vippk0000** [comment]
Awesome, it worked 👍
